"""
Django settings for schedule_optimizer project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import django_heroku
django_heroku.settings(locals())
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h^r&*babdqzxp0itu=r*3d-j@!rk-=6rvxdbe2wv9wx6cx3h8$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'scheduler',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'schedule_optimizer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/ 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'schedule_optimizer.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'timetable_db',      # اسم قاعدة البيانات
#         'USER': 'timetable_timetable',          # اسم المستخدم
#         'PASSWORD': '(ORB3-G4wq#I',  # كلمة المرور
#         'HOST': 'localhost',       # عنوان الخادم
#         'PORT': '5432',            # المنفذ الافتراضي لـ PostgreSQL
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# المسار الذي سيتم جمع الملفات الثابتة فيه عندما تقوم بتشغيل أمر collectstatic
STATIC_ROOT = BASE_DIR / 'static'

# المواقع التي تحتوي على ملفات ثابتة خاصة بتطبيقات Django
STATICFILES_DIRS = [
    BASE_DIR / 'schedule_optimizer/static',  # أو المسار إلى المجلد الذي يحتوي على ملفات الستاتيك الخاصة بك
]
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

import os

# إعدادات المسارات للملفات الإعلامية
MEDIA_URL = '/media/'  # URL للوصول للملفات
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # المسار الفعلي لتخزين الملفات

# تحديد مدة انتهاء الجلسة بعد 15 دقيقة من عدم النشاط (بالثواني)
SESSION_COOKIE_AGE = 900  # 15 دقيقة = 15 * 60 = 900 ثانية

# تفعيل خاصية انتهاء الجلسة عند إغلاق المتصفح
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# (اختياري) تفعيل انتهاء الجلسة بعد فترة عدم النشاط
SESSION_SAVE_EVERY_REQUEST = True


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_ENGINE = "django.contrib.sessions.backends.db"  # تأكد من استخدام الجلسات المعتمدة على قاعدة البيانات
SESSION_SAVE_EVERY_REQUEST = True  # احفظ الجلسة بعد كل طلب
