# Generated by Django 5.1.3 on 2024-11-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Professor",
            new_name="Lecturer",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="professor",
            new_name="Lecturer",
        ),
    ]
