# Generated by Django 5.1.3 on 2024-11-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0003_semester_course_student_count_course_semester"),
    ]

    operations = [
        migrations.RenameField(
            model_name="semester",
            old_name="number",
            new_name="semester_number",
        ),
    ]
