# Generated by Django 5.1.3 on 2024-11-08 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0004_rename_number_semester_semester_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="semester",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scheduler.semester",
            ),
        ),
    ]
