# Generated by Django 5.1.3 on 2024-11-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0005_department_semester"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="semester",
        ),
    ]
