# Generated by Django 5.1.3 on 2024-11-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0006_remove_course_semester"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="Lecturer",
            new_name="lecturer",
        ),
        migrations.AddField(
            model_name="semester",
            name="semester_name",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.RemoveField(
            model_name="course",
            name="department",
        ),
        migrations.AddField(
            model_name="course",
            name="department",
            field=models.ManyToManyField(to="scheduler.department"),
        ),
    ]
