# Generated by Django 5.1.3 on 2024-11-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0007_rename_lecturer_course_lecturer_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TimeSlot",
        ),
    ]
