# Generated by Django 5.1.3 on 2025-01-02 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0009_college"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="college",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="scheduler.college",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="college",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="scheduler.college",
            ),
        ),
        migrations.AddField(
            model_name="lecturer",
            name="college",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="scheduler.college",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="college",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="scheduler.college",
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="college",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="scheduler.college",
            ),
        ),
    ]
