# Generated by Django 5.1.3 on 2025-01-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scheduler",
            "0010_course_college_department_college_lecturer_college_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
    ]
