# Generated by Django 5.1.3 on 2025-01-03 17:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0011_term"),
    ]

    operations = [
        migrations.AddField(
            model_name="term",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
