# Generated by Django 5.1.3 on 2025-01-03 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0012_term_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="scheduler.college"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="scheduler.college"
            ),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="scheduler.college"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="scheduler.college"
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="scheduler.college"
            ),
        ),
    ]
