# Generated by Django 5.1.3 on 2025-01-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0013_alter_course_college_alter_department_college_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="college",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="college_logos/"),
        ),
    ]
