# Generated by Django 5.1.3 on 2025-01-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0016_course_required_room_type_room_room_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("hall", "قاعة"),
                    ("computer_lab", "معمل حاسوب"),
                    ("chemistry_lab", "معمل كيمياء"),
                    ("rocks_lab", "معمل صخور"),
                    ("biology_lab", "معمل أحياء"),
                    ("movable_prosthetics_lab", "معمل التركيبات المتحركة"),
                    ("dental_lab", "معمل صناعة الأسنان"),
                    ("fixed_prosthetics_lab", "معمل التركيبات الثابتة"),
                    ("casting_lab", "معمل الصب"),
                    ("conservative_lab", "معمل العلاج التحفظي"),
                ],
                default="hall",
                max_length=40,
            ),
        ),
    ]
