# Generated by Django 3.2.25 on 2025-02-04 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0020_days_periods'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.college')),
                ('days', models.ManyToManyField(to='scheduler.Days')),
                ('periods', models.ManyToManyField(to='scheduler.Periods')),
            ],
        ),
    ]
